### PR TITLE
Update 'react-native-tab-view' to latest

### PR DESCRIPTION
**Pull request by satya164**
The latest version fixes a nasty bug where interaction manager handle was not cleared when the component is updated during a swipe gesture

### CODE REVIEW

**Comment by satya164** [comment]
Don't merge this yet. I think I might have a better fix.

**Comment by satya164** [comment]
The latest version should be good to go. cc @skevy

**Comment by chirag04** [comment]
@brentvatne @skevy ping

**Comment by skevy** [comment]
@satya164 just double checking that everything's good to go here?

**Comment by satya164** [comment]
@skevy 👍

**Comment by skevy** [comment]
Awesome sauce.

**Pull request closed without merging**
