### PR TITLE
Improve FloatVertical transition

### PR DESCRIPTION
**Pull request by samuelkraft**
Makes the FloatVertical transition look more native to iOS (no scale/opacity changes)

### CODE REVIEW

**Comment by chirag04** [comment]
how would break on android tho? I guess we have `scale` on android?

cc @brentvatne

**Comment by samuelkraft** [comment]
Something similar to https://github.com/exponentjs/ex-navigation/pull/84 might be better to keep the current one for android?

**Comment by samuelkraft** [comment]
(FloatVerticalIOS instead of overwriting)

**Comment by brentvatne** [comment]
@samuelkraft - maybe we can just add a conditional in here to do scale etc. on Android?

**Comment by samuelkraft** [comment]
@brentvatne That could work, but in case you want the same transition on ios and android you might get confused when FloatVertical behaves differently. 

I'd add FloatVerticalIOS and keep FloatVertical for android, and use those as defaults. So unless you change it you would get the platform standard.

**Comment by samuelkraft** [comment]
@brentvatne @chirag04 Added SlideVerticalIOS and kept FloatVertical for android to match #84

**Comment by skevy** [comment]
I would rather just call this `SlideVertical`, rather than `SlideVerticalIOS`.

**Comment by samuelkraft** [comment]
@skevy Updated the pr

**Comment by chirag04** [comment]
I just tried the `SlideVertical`. Def looks awesome on ios.

what's the plan for FloatVertical and android tho?

**Pull request closed without merging**
