### PR TITLE
remove react and react-native as deps

### PR DESCRIPTION
**Pull request by chirag04**
@skevy @brentvatne not sure y we need them as deps.

### CODE REVIEW

**Comment by brentvatne** [comment]
@chirag04 - when you're working on ex-navigation you need to have these available in node_modules in order for flow to work

**Comment by chirag04** [comment]
haven't used flow much so not sure how this works but this does not look right.

**Comment by brentvatne** [comment]
cc @skevy

**Comment by skevy** [comment]
does this affect you as a user of ex-nav? I think this is fine, given what @brentvatne said about flow. These have to be there. It probably doesn't look right because most react native libraries (outside of core) don't use flow :)

**Comment by chirag04** [comment]
I just doubled checked my understanding of devdeps. You are right, this doesn't affect me for sure. Sorry for the confusion :)

**Pull request closed without merging**
