### PR TITLE
add screen tracking recipe

### PR DESCRIPTION
**Pull request by chirag04**
@skevy @brentvatne just wanted to throw it out here for anyone who might have a similar problem

### CODE REVIEW

**Comment by chirag04** [comment]
feedback on improving the middleware would be awesome. idk if it's worth being specific about which actions would change the screen like the way it's done in `ExNavigationMiddlewares`

**Comment by sibelius** [comment]
@chirag04 what do u think to start a recipes folder for ex-navigation following the idea of avajs?

https://github.com/avajs/ava#recipes

**Comment by chirag04** [comment]
yeah sure. recipes sound like a good idea. we can link all the recipes in the README.md

**Comment by sibelius** [comment]
yep, we can get some recipes from this gist: https://gist.github.com/knowbody/ce483742a1761658b767428a0ed35147

**Comment by sibelius** [comment]
@chirag04 I'll add your recipe to https://github.com/sibelius/ex-navigation-recipes

**Pull request closed without merging**
